export default {
  repo: [
    {type: 'doc', id: 'docs/project', label: 'Концепция и комплект'},
    {type: 'doc', id: 'docs/plan', label: 'План работ'},
    {
      type: 'category',
      label: 'Исследования',
      link: {type: 'doc', id: 'research/README'},
      items: [{type: 'autogenerated', dirName: 'research'}],
    },
    {type: 'category', label: 'Расчёты', items: [{type: 'autogenerated', dirName: 'calc'}]},
    {type: 'doc', id: 'ecu/README', label: 'Настройки rusEFI'},
  ],
};
